spring.application.name=crowdfunding_project
spring.datasource.url=jdbc:mysql://localhost:3306/crowdfunding_db?createDatabaseIfNotExist=true
spring.datasource.username= root
spring.datasource.password=ton_mot_de_passe
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true