spring.application.name=crowdfunding_project

# ── Base de donnees ───────────────────────────────────────────
spring.datasource.url=jdbc:mysql://localhost:3306/crowdfunding_db
spring.datasource.username=root
spring.datasource.password=manalbhll$123$#&&
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.open-in-view=false

# ── JPA / Hibernate ───────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ── JWT ───────────────────────────────────────────────────────
jwt.secret=myVeryLongSecretKeyThatContainsAtLeast32Characters123
jwt.expiration=86400000

# ── OTP ───────────────────────────────────────────────────────
otp.length=6
otp.expiry-minutes=15
otp.max-attempts=5
otp.max-generations=5

# ── Mail ──────────────────────────────────────────────────────
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=crowdfundingensias@gmail.com
spring.mail.password=pejb coye uoei acip
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# DEV : mettre false pour envoyer de vrais emails
app.email.disabled=false

# ── Thymeleaf ─────────────────────────────────────────────────
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

#── Chemin où seront stockés les fichiers uploadés──────────────────
file.upload-dir=uploads/kyc
# Taille maximale d’un fichier (10 Mo)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# ── Frontend ──────────────────────────────────────────────────
app.frontend.url=http://localhost:5173