spring.application.name=crowdfunding_project
# URL de connexion (crowdfunding_db est le nom de la DB créée plus haut)
spring.datasource.url=jdbc:mysql://localhost:3306/crowdfunding_db
spring.datasource.username= root
spring.datasource.password= the6black9dragon
# Pilote MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate configuration
# 'update' permet à Spring de créer/modifier les tables automatiquement selon tes entités Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
jwt.secret=myVeryLongSecretKeyThatContainsAtLeast32Characters123
jwt.expiration=86400000